@echo off
@echo Changing directory...
cd %~dp0
@echo Creating virtual environment...
call python -m venv environment
@echo Activating virtual environment...
call environment\Scripts\activate
@echo Installing requirements...
call pip install -r requirements.txt
@echo Deactivating virtual environment...
deactivate
@echo JAUB installed.