@echo off
@echo Changing directory...
cd %~dp0
@echo Activating environment...
call environment\Scripts\activate
@echo Starting bot...
python bot.py
@echo Deactivating environment...
deactivate