@echo off
@echo Changing directory...
cd C:\Python\Discord Bot\
@echo Activating environment...
call environment\Scripts\activate
@echo Starting bot...
python bot.py
@echo Deactivating environment...
deactivate